### ISSUE TITLE
when will you open source your code?

### ISSUE THREAD

**Issue by chuanHN** [yuedongP/EditNTS#2]
Hi, I have read your paper in ACL2019 and am interested in your paper. so I want to know whether you will make your code public or not.

**Comment by fredrijo** [comment]
I share the interest: Great paper at ACL this year, and I would really like to see the source code.

**Comment by siangooding** [comment]
Same! Great paper, would be cool to see the output of the model too.

**Comment by Noixas** [comment]
I third that! The paper looks great, would love to play with the model and see the output.

**Comment by YueDongCS** [comment]
Hello all, I just upload the code and please contact me if you have any questions. Thanks for your interests in our paper!
